# Generated by Django 3.2 on 2021-04-30 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frama_app', '0002_auto_20210429_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='contents',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='directory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
