# Generated by Django 3.2.3 on 2021-05-18 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frama_app', '0004_auto_20210514_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frama_app.directory'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_object',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frama_app.directory'),
        ),
    ]
