# Generated by Django 3.2.3 on 2021-05-19 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frama_app', '0005_auto_20210518_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='parent_section',
        ),
        migrations.AddField(
            model_name='section',
            name='line',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.IntegerField(choices=[('requires', 'Requires'), ('ensures', 'Ensures'), ('variant', 'Variant'), ('invariant', 'Invariant'), ('predicate', 'Predicate')]),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='section',
            name='status',
            field=models.IntegerField(blank=True, choices=[('Unknown', 'Unknown'), ('Valid', 'Valid'), ('Invalid', 'Invalid'), ('Timeout', 'Timeout')]),
        ),
        migrations.AlterField(
            model_name='section',
            name='status_data',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='frama_app.statusdata'),
        ),
    ]
