# Generated by Django 3.2.3 on 2021-05-19 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frama_app', '0006_auto_20210519_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.CharField(choices=[('requires', 'Requires'), ('ensures', 'Ensures'), ('variant', 'Variant'), ('invariant', 'Invariant'), ('predicate', 'Predicate'), ('ghost', 'Ghost'), ('assert', 'Assert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='status',
            field=models.CharField(blank=True, choices=[('Unknown', 'Unknown'), ('Valid', 'Valid'), ('Invalid', 'Invalid'), ('Timeout', 'Timeout')], max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='status_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frama_app.statusdata'),
        ),
    ]
