# Generated by Django 3.2.3 on 2021-05-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frama_app', '0007_auto_20210519_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='frama_output',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='section',
            name='category',
            field=models.CharField(choices=[('requires', 'Requires'), ('ensures', 'Ensures'), ('variant', 'Variant'), ('invariant', 'Invariant'), ('predicate', 'Predicate'), ('ghost', 'Ghost'), ('assert', 'Assert'), ('lemma', 'Lemma'), ('assigns', 'Assigns'), ('exits', 'Exits'), ('check', 'Check'), ('breaks', 'Breaks'), ('continues', 'Continues'), ('returns', 'Returns')], max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='status',
            field=models.CharField(blank=True, choices=[('lightgray', 'Unknown'), ('mediumseagreen', 'Valid'), ('red', 'Invalid'), ('mediumslateblue', 'Timeout')], max_length=20),
        ),
    ]
